version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./Accident_Severity_Prediction:/app/Accident_Severity_Prediction
    environment:
      - PYTHONIOENCODING=utf-8
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - PYTHONPATH=/app
    restart: unless-stopped